// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"database/sql"
)

const createAuditEntry = `-- name: CreateAuditEntry :exec
INSERT INTO audit_entries (id, created_at, user_id, patient_id, action, entity_type, entity_id, fields_changed, ip_address, user_agent)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditEntryParams struct {
	ID            string
	CreatedAt     string
	UserID        string
	PatientID     sql.NullString
	Action        string
	EntityType    string
	EntityID      string
	FieldsChanged string
	IPAddress     string
	UserAgent     string
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, createAuditEntry,
		arg.ID, arg.CreatedAt, arg.UserID, arg.PatientID, arg.Action,
		arg.EntityType, arg.EntityID, arg.FieldsChanged, arg.IPAddress, arg.UserAgent,
	)
	return err
}

const getAuditEntriesByPatientID = `-- name: GetAuditEntriesByPatientID :many
SELECT id, created_at, user_id, patient_id, action, entity_type, entity_id, fields_changed, ip_address, user_agent
FROM audit_entries
WHERE patient_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetAuditEntriesByPatientID(ctx context.Context, patientID sql.NullString) ([]AuditEntry, error) {
	rows, err := q.db.QueryContext(ctx, getAuditEntriesByPatientID, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID, &i.CreatedAt, &i.UserID, &i.PatientID, &i.Action,
			&i.EntityType, &i.EntityID, &i.FieldsChanged, &i.IPAddress, &i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditEntriesByEntity = `-- name: GetAuditEntriesByEntity :many
SELECT id, created_at, user_id, patient_id, action, entity_type, entity_id, fields_changed, ip_address, user_agent
FROM audit_entries
WHERE entity_type = ? AND entity_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetAuditEntriesByEntity(ctx context.Context, entityType string, entityID string) ([]AuditEntry, error) {
	rows, err := q.db.QueryContext(ctx, getAuditEntriesByEntity, entityType, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEntry{}
	for rows.Next() {
		var i AuditEntry
		if err := rows.Scan(
			&i.ID, &i.CreatedAt, &i.UserID, &i.PatientID, &i.Action,
			&i.EntityType, &i.EntityID, &i.FieldsChanged, &i.IPAddress, &i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
