// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

const createEmergencyContact = `-- name: CreateEmergencyContact :exec
INSERT INTO emergency_contacts (id, created_at, updated_at, patient_id, name, relationship, phone, email, is_primary)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEmergencyContactParams struct {
	ID           string
	CreatedAt    string
	UpdatedAt    string
	PatientID    string
	Name         string
	Relationship string
	Phone        string
	Email        string
	IsPrimary    int64
}

func (q *Queries) CreateEmergencyContact(ctx context.Context, arg CreateEmergencyContactParams) error {
	_, err := q.db.ExecContext(ctx, createEmergencyContact,
		arg.ID, arg.CreatedAt, arg.UpdatedAt, arg.PatientID,
		arg.Name, arg.Relationship, arg.Phone, arg.Email, arg.IsPrimary,
	)
	return err
}

const deleteEmergencyContact = `-- name: DeleteEmergencyContact :exec
DELETE FROM emergency_contacts WHERE id = ?
`

func (q *Queries) DeleteEmergencyContact(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEmergencyContact, id)
	return err
}

const getEmergencyContactsByPatientID = `-- name: GetEmergencyContactsByPatientID :many
SELECT id, created_at, updated_at, patient_id, name, relationship, phone, email, is_primary
FROM emergency_contacts WHERE patient_id = ? ORDER BY is_primary DESC, name
`

func (q *Queries) GetEmergencyContactsByPatientID(ctx context.Context, patientID string) ([]EmergencyContact, error) {
	rows, err := q.db.QueryContext(ctx, getEmergencyContactsByPatientID, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmergencyContact{}
	for rows.Next() {
		var i EmergencyContact
		if err := rows.Scan(
			&i.ID, &i.CreatedAt, &i.UpdatedAt, &i.PatientID,
			&i.Name, &i.Relationship, &i.Phone, &i.Email, &i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
