// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"database/sql"
)

const createHealthHistory = `-- name: CreateHealthHistory :exec
INSERT INTO health_history (id, created_at, patient_id, recorded_by, condition, date_occurred, description, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateHealthHistoryParams struct {
	ID           string
	CreatedAt    string
	PatientID    string
	RecordedBy   string
	Condition    string
	DateOccurred sql.NullString
	Description  string
	Status       string
}

func (q *Queries) CreateHealthHistory(ctx context.Context, arg CreateHealthHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createHealthHistory,
		arg.ID, arg.CreatedAt, arg.PatientID, arg.RecordedBy,
		arg.Condition, arg.DateOccurred, arg.Description, arg.Status,
	)
	return err
}

const getHealthHistoryByPatientID = `-- name: GetHealthHistoryByPatientID :many
SELECT id, created_at, patient_id, recorded_by, condition, date_occurred, description, status
FROM health_history WHERE patient_id = ? ORDER BY created_at DESC
`

func (q *Queries) GetHealthHistoryByPatientID(ctx context.Context, patientID string) ([]HealthHistory, error) {
	rows, err := q.db.QueryContext(ctx, getHealthHistoryByPatientID, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HealthHistory{}
	for rows.Next() {
		var i HealthHistory
		if err := rows.Scan(
			&i.ID, &i.CreatedAt, &i.PatientID, &i.RecordedBy,
			&i.Condition, &i.DateOccurred, &i.Description, &i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
