// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT id, created_at, idempotency_key, response
FROM idempotency_records
WHERE idempotency_key = ?
`

func (q *Queries) GetIdempotencyRecord(ctx context.Context, idempotencyKey string) (IdempotencyRecord, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyRecord, idempotencyKey)
	var i IdempotencyRecord
	err := row.Scan(&i.ID, &i.CreatedAt, &i.IdempotencyKey, &i.Response)
	return i, err
}

const createIdempotencyRecord = `-- name: CreateIdempotencyRecord :exec
INSERT INTO idempotency_records (id, created_at, idempotency_key, response)
VALUES (?, ?, ?, ?)
`

type CreateIdempotencyRecordParams struct {
	ID             string
	CreatedAt      string
	IdempotencyKey string
	Response       string
}

func (q *Queries) CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) error {
	_, err := q.db.ExecContext(ctx, createIdempotencyRecord,
		arg.ID, arg.CreatedAt, arg.IdempotencyKey, arg.Response,
	)
	return err
}
