// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"database/sql"
)

const createMAREntry = `-- name: CreateMAREntry :exec
INSERT INTO mar_entries (id, created_at, patient_id, medication_id, scheduled_time, administered_at, administered_by, status, dose, route, site, hold_reason, notes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMAREntryParams struct {
	ID             string
	CreatedAt      string
	PatientID      string
	MedicationID   string
	ScheduledTime  string
	AdministeredAt sql.NullString
	AdministeredBy sql.NullString
	Status         string
	Dose           string
	Route          string
	Site           string
	HoldReason     string
	Notes          string
}

func (q *Queries) CreateMAREntry(ctx context.Context, arg CreateMAREntryParams) error {
	_, err := q.db.ExecContext(ctx, createMAREntry,
		arg.ID, arg.CreatedAt, arg.PatientID, arg.MedicationID,
		arg.ScheduledTime, arg.AdministeredAt, arg.AdministeredBy,
		arg.Status, arg.Dose, arg.Route, arg.Site, arg.HoldReason, arg.Notes,
	)
	return err
}

const updateMAREntry = `-- name: UpdateMAREntry :exec
UPDATE mar_entries SET administered_at = ?, administered_by = ?, status = ?, hold_reason = ?, notes = ?
WHERE id = ?
`

func (q *Queries) UpdateMAREntry(ctx context.Context, administeredAt sql.NullString, administeredBy sql.NullString, status string, holdReason string, notes string, id string) error {
	_, err := q.db.ExecContext(ctx, updateMAREntry, administeredAt, administeredBy, status, holdReason, notes, id)
	return err
}

const getMAREntriesByPatientID = `-- name: GetMAREntriesByPatientID :many
SELECT id, created_at, patient_id, medication_id, scheduled_time, administered_at, administered_by, status, dose, route, site, hold_reason, notes
FROM mar_entries WHERE patient_id = ? ORDER BY scheduled_time DESC
`

func (q *Queries) GetMAREntriesByPatientID(ctx context.Context, patientID string) ([]MAREntry, error) {
	rows, err := q.db.QueryContext(ctx, getMAREntriesByPatientID, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MAREntry{}
	for rows.Next() {
		var i MAREntry
		if err := rows.Scan(
			&i.ID, &i.CreatedAt, &i.PatientID, &i.MedicationID,
			&i.ScheduledTime, &i.AdministeredAt, &i.AdministeredBy,
			&i.Status, &i.Dose, &i.Route, &i.Site, &i.HoldReason, &i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getMAREntryByID = `-- name: GetMAREntryByID :one
SELECT id, created_at, patient_id, medication_id, scheduled_time, administered_at, administered_by, status, dose, route, site, hold_reason, notes
FROM mar_entries WHERE id = ?
`

func (q *Queries) GetMAREntryByID(ctx context.Context, id string) (MAREntry, error) {
	row := q.db.QueryRowContext(ctx, getMAREntryByID, id)
	var i MAREntry
	err := row.Scan(
		&i.ID, &i.CreatedAt, &i.PatientID, &i.MedicationID,
		&i.ScheduledTime, &i.AdministeredAt, &i.AdministeredBy,
		&i.Status, &i.Dose, &i.Route, &i.Site, &i.HoldReason, &i.Notes,
	)
	return i, err
}
