// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

const createMedication = `-- name: CreateMedication :exec
INSERT INTO medications (id, created_at, updated_at, name, brand_name, drug_class, ndc_code, default_dose, default_route, frequency, high_alert)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMedicationParams struct {
	ID           string
	CreatedAt    string
	UpdatedAt    string
	Name         string
	BrandName    string
	DrugClass    string
	NdcCode      string
	DefaultDose  string
	DefaultRoute string
	Frequency    string
	HighAlert    int64
}

func (q *Queries) CreateMedication(ctx context.Context, arg CreateMedicationParams) error {
	_, err := q.db.ExecContext(ctx, createMedication,
		arg.ID, arg.CreatedAt, arg.UpdatedAt, arg.Name, arg.BrandName,
		arg.DrugClass, arg.NdcCode, arg.DefaultDose, arg.DefaultRoute,
		arg.Frequency, arg.HighAlert,
	)
	return err
}

const getMedicationByID = `-- name: GetMedicationByID :one
SELECT id, created_at, updated_at, deleted_at, name, brand_name, drug_class, ndc_code, default_dose, default_route, frequency, high_alert
FROM medications WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetMedicationByID(ctx context.Context, id string) (Medication, error) {
	row := q.db.QueryRowContext(ctx, getMedicationByID, id)
	var i Medication
	err := row.Scan(
		&i.ID, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt, &i.Name, &i.BrandName,
		&i.DrugClass, &i.NdcCode, &i.DefaultDose, &i.DefaultRoute,
		&i.Frequency, &i.HighAlert,
	)
	return i, err
}

const getAllMedications = `-- name: GetAllMedications :many
SELECT id, created_at, updated_at, deleted_at, name, brand_name, drug_class, ndc_code, default_dose, default_route, frequency, high_alert
FROM medications WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) GetAllMedications(ctx context.Context) ([]Medication, error) {
	rows, err := q.db.QueryContext(ctx, getAllMedications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medication{}
	for rows.Next() {
		var i Medication
		if err := rows.Scan(
			&i.ID, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt, &i.Name, &i.BrandName,
			&i.DrugClass, &i.NdcCode, &i.DefaultDose, &i.DefaultRoute,
			&i.Frequency, &i.HighAlert,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
