// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
)

type AuditEntry struct {
	ID            string
	CreatedAt     string
	UserID        string
	PatientID     sql.NullString
	Action        string
	EntityType    string
	EntityID      string
	FieldsChanged string
	IPAddress     string
	UserAgent     string
}

type IdempotencyRecord struct {
	ID             string
	CreatedAt      string
	IdempotencyKey string
	Response       string
}

type Patient struct {
	ID              string
	CreatedAt       string
	UpdatedAt       string
	DeletedAt       sql.NullString
	Mrn             string
	FirstName       string
	LastName        string
	DateOfBirth     string
	RoomBed         string
	Allergies       string
	Diagnoses       string
	CodeStatus      string
	FallRisk        int64
	IsolationType   string
	AdmitDate       string
	DischargeDate   sql.NullString
	AssignedNurseID sql.NullString
}

type User struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	DeletedAt sql.NullString
	Username  string
	FullName  string
	Role      string
	Unit      string
	BadgeID   string
	Active    int64
}

type VitalSign struct {
	ID             string
	CreatedAt      string
	PatientID      string
	RecordedBy     string
	SystolicBp     sql.NullInt64
	DiastolicBp    sql.NullInt64
	HeartRate      sql.NullInt64
	Temperature    sql.NullFloat64
	TempRoute      sql.NullString
	OxygenSat      sql.NullInt64
	Respirations   sql.NullInt64
	PainLevel      sql.NullInt64
	SupplementalO2 int64
	O2FlowRate     sql.NullFloat64
	Position       sql.NullString
	Notes          string
}

type Medication struct {
	ID           string
	CreatedAt    string
	UpdatedAt    string
	DeletedAt    sql.NullString
	Name         string
	BrandName    string
	DrugClass    string
	NdcCode      string
	DefaultDose  string
	DefaultRoute string
	Frequency    string
	HighAlert    int64
}

type MAREntry struct {
	ID             string
	CreatedAt      string
	PatientID      string
	MedicationID   string
	ScheduledTime  string
	AdministeredAt sql.NullString
	AdministeredBy sql.NullString
	Status         string
	Dose           string
	Route          string
	Site           string
	HoldReason     string
	Notes          string
}

type VaccinationRecord struct {
	ID               string
	CreatedAt        string
	PatientID        string
	RecordedBy       string
	VaccineName      string
	DateAdministered string
	LotNumber        string
	Site             string
	Notes            string
}

type HealthHistory struct {
	ID           string
	CreatedAt    string
	PatientID    string
	RecordedBy   string
	Condition    string
	DateOccurred sql.NullString
	Description  string
	Status       string
}

type EmergencyContact struct {
	ID           string
	CreatedAt    string
	UpdatedAt    string
	PatientID    string
	Name         string
	Relationship string
	Phone        string
	Email        string
	IsPrimary    int64
}

type Task struct {
	ID            string
	CreatedAt     string
	UpdatedAt     string
	PatientID     string
	AssignedTo    string
	Title         string
	Category      string
	DueAt         string
	CompletedAt   sql.NullString
	CompletedBy   sql.NullString
	Priority      string
	Recurring     int64
	RecurInterval sql.NullString
	Notes         string
}
