// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"database/sql"
)

const createPatient = `-- name: CreatePatient :exec
INSERT INTO patients (id, created_at, updated_at, mrn, first_name, last_name, date_of_birth, room_bed, allergies, diagnoses, code_status, fall_risk, isolation_type, admit_date, discharge_date, assigned_nurse_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePatientParams struct {
	ID              string
	CreatedAt       string
	UpdatedAt       string
	Mrn             string
	FirstName       string
	LastName        string
	DateOfBirth     string
	RoomBed         string
	Allergies       string
	Diagnoses       string
	CodeStatus      string
	FallRisk        int64
	IsolationType   string
	AdmitDate       string
	DischargeDate   sql.NullString
	AssignedNurseID sql.NullString
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) error {
	_, err := q.db.ExecContext(ctx, createPatient,
		arg.ID, arg.CreatedAt, arg.UpdatedAt, arg.Mrn, arg.FirstName, arg.LastName,
		arg.DateOfBirth, arg.RoomBed, arg.Allergies, arg.Diagnoses, arg.CodeStatus,
		arg.FallRisk, arg.IsolationType, arg.AdmitDate, arg.DischargeDate, arg.AssignedNurseID,
	)
	return err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT id, created_at, updated_at, mrn, first_name, last_name, date_of_birth, room_bed, allergies, diagnoses, code_status, fall_risk, isolation_type, admit_date, discharge_date, assigned_nurse_id
FROM patients
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetPatientByID(ctx context.Context, id string) (Patient, error) {
	row := q.db.QueryRowContext(ctx, getPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID, &i.CreatedAt, &i.UpdatedAt, &i.Mrn, &i.FirstName, &i.LastName,
		&i.DateOfBirth, &i.RoomBed, &i.Allergies, &i.Diagnoses, &i.CodeStatus,
		&i.FallRisk, &i.IsolationType, &i.AdmitDate, &i.DischargeDate, &i.AssignedNurseID,
	)
	return i, err
}

const getAdmittedPatients = `-- name: GetAdmittedPatients :many
SELECT id, created_at, updated_at, mrn, first_name, last_name, date_of_birth, room_bed, allergies, diagnoses, code_status, fall_risk, isolation_type, admit_date, discharge_date, assigned_nurse_id
FROM patients
WHERE discharge_date IS NULL AND deleted_at IS NULL
ORDER BY room_bed
`

func (q *Queries) GetAdmittedPatients(ctx context.Context) ([]Patient, error) {
	rows, err := q.db.QueryContext(ctx, getAdmittedPatients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Patient{}
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID, &i.CreatedAt, &i.UpdatedAt, &i.Mrn, &i.FirstName, &i.LastName,
			&i.DateOfBirth, &i.RoomBed, &i.Allergies, &i.Diagnoses, &i.CodeStatus,
			&i.FallRisk, &i.IsolationType, &i.AdmitDate, &i.DischargeDate, &i.AssignedNurseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatient = `-- name: UpdatePatient :exec
UPDATE patients
SET updated_at = ?, first_name = ?, last_name = ?, room_bed = ?, allergies = ?, diagnoses = ?, code_status = ?, fall_risk = ?, isolation_type = ?, assigned_nurse_id = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdatePatientParams struct {
	UpdatedAt       string
	FirstName       string
	LastName        string
	RoomBed         string
	Allergies       string
	Diagnoses       string
	CodeStatus      string
	FallRisk        int64
	IsolationType   string
	AssignedNurseID sql.NullString
	ID              string
}

func (q *Queries) UpdatePatient(ctx context.Context, arg UpdatePatientParams) error {
	_, err := q.db.ExecContext(ctx, updatePatient,
		arg.UpdatedAt, arg.FirstName, arg.LastName, arg.RoomBed, arg.Allergies,
		arg.Diagnoses, arg.CodeStatus, arg.FallRisk, arg.IsolationType,
		arg.AssignedNurseID, arg.ID,
	)
	return err
}

const dischargePatient = `-- name: DischargePatient :exec
UPDATE patients
SET updated_at = ?, discharge_date = ?
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) DischargePatient(ctx context.Context, updatedAt string, dischargeDate sql.NullString, id string) error {
	_, err := q.db.ExecContext(ctx, dischargePatient, updatedAt, dischargeDate, id)
	return err
}

const softDeletePatient = `-- name: SoftDeletePatient :exec
UPDATE patients SET deleted_at = ? WHERE id = ?
`

func (q *Queries) SoftDeletePatient(ctx context.Context, deletedAt string, id string) error {
	_, err := q.db.ExecContext(ctx, softDeletePatient, deletedAt, id)
	return err
}
