// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (id, created_at, updated_at, patient_id, assigned_to, title, category, due_at, completed_at, completed_by, priority, recurring, recur_interval, notes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	ID            string
	CreatedAt     string
	UpdatedAt     string
	PatientID     string
	AssignedTo    string
	Title         string
	Category      string
	DueAt         string
	CompletedAt   sql.NullString
	CompletedBy   sql.NullString
	Priority      string
	Recurring     int64
	RecurInterval sql.NullString
	Notes         string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID, arg.CreatedAt, arg.UpdatedAt, arg.PatientID,
		arg.AssignedTo, arg.Title, arg.Category, arg.DueAt,
		arg.CompletedAt, arg.CompletedBy, arg.Priority,
		arg.Recurring, arg.RecurInterval, arg.Notes,
	)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks SET updated_at = ?, completed_at = ?, completed_by = ?, notes = ?
WHERE id = ?
`

func (q *Queries) UpdateTask(ctx context.Context, updatedAt string, completedAt sql.NullString, completedBy sql.NullString, notes string, id string) error {
	_, err := q.db.ExecContext(ctx, updateTask, updatedAt, completedAt, completedBy, notes, id)
	return err
}

const getTasksByPatientID = `-- name: GetTasksByPatientID :many
SELECT id, created_at, updated_at, patient_id, assigned_to, title, category, due_at, completed_at, completed_by, priority, recurring, recur_interval, notes
FROM tasks WHERE patient_id = ? ORDER BY due_at ASC
`

func (q *Queries) GetTasksByPatientID(ctx context.Context, patientID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByPatientID, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID, &i.CreatedAt, &i.UpdatedAt, &i.PatientID,
			&i.AssignedTo, &i.Title, &i.Category, &i.DueAt,
			&i.CompletedAt, &i.CompletedBy, &i.Priority,
			&i.Recurring, &i.RecurInterval, &i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, created_at, updated_at, patient_id, assigned_to, title, category, due_at, completed_at, completed_by, priority, recurring, recur_interval, notes
FROM tasks WHERE id = ?
`

func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID, &i.CreatedAt, &i.UpdatedAt, &i.PatientID,
		&i.AssignedTo, &i.Title, &i.Category, &i.DueAt,
		&i.CompletedAt, &i.CompletedBy, &i.Priority,
		&i.Recurring, &i.RecurInterval, &i.Notes,
	)
	return i, err
}
