// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, created_at, updated_at, username, full_name, role, unit, badge_id, active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Username  string
	FullName  string
	Role      string
	Unit      string
	BadgeID   string
	Active    int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID, arg.CreatedAt, arg.UpdatedAt, arg.Username, arg.FullName, arg.Role, arg.Unit, arg.BadgeID, arg.Active,
	)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, username, full_name, role, unit, badge_id, active
FROM users
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID, &i.CreatedAt, &i.UpdatedAt, &i.Username, &i.FullName, &i.Role, &i.Unit, &i.BadgeID, &i.Active,
	)
	return i, err
}

const getAllActiveUsers = `-- name: GetAllActiveUsers :many
SELECT id, created_at, updated_at, username, full_name, role, unit, badge_id, active
FROM users
WHERE active = 1 AND deleted_at IS NULL
ORDER BY full_name
`

func (q *Queries) GetAllActiveUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID, &i.CreatedAt, &i.UpdatedAt, &i.Username, &i.FullName, &i.Role, &i.Unit, &i.BadgeID, &i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET updated_at = ?, username = ?, full_name = ?, role = ?, unit = ?, badge_id = ?, active = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserParams struct {
	UpdatedAt string
	Username  string
	FullName  string
	Role      string
	Unit      string
	BadgeID   string
	Active    int64
	ID        string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.UpdatedAt, arg.Username, arg.FullName, arg.Role, arg.Unit, arg.BadgeID, arg.Active, arg.ID,
	)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = ? WHERE id = ?
`

func (q *Queries) SoftDeleteUser(ctx context.Context, deletedAt string, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, deletedAt, id)
	return err
}
