// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

const createVaccinationRecord = `-- name: CreateVaccinationRecord :exec
INSERT INTO vaccination_records (id, created_at, patient_id, recorded_by, vaccine_name, date_administered, lot_number, site, notes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateVaccinationRecordParams struct {
	ID               string
	CreatedAt        string
	PatientID        string
	RecordedBy       string
	VaccineName      string
	DateAdministered string
	LotNumber        string
	Site             string
	Notes            string
}

func (q *Queries) CreateVaccinationRecord(ctx context.Context, arg CreateVaccinationRecordParams) error {
	_, err := q.db.ExecContext(ctx, createVaccinationRecord,
		arg.ID, arg.CreatedAt, arg.PatientID, arg.RecordedBy,
		arg.VaccineName, arg.DateAdministered, arg.LotNumber, arg.Site, arg.Notes,
	)
	return err
}

const getVaccinationRecordsByPatientID = `-- name: GetVaccinationRecordsByPatientID :many
SELECT id, created_at, patient_id, recorded_by, vaccine_name, date_administered, lot_number, site, notes
FROM vaccination_records WHERE patient_id = ? ORDER BY date_administered DESC
`

func (q *Queries) GetVaccinationRecordsByPatientID(ctx context.Context, patientID string) ([]VaccinationRecord, error) {
	rows, err := q.db.QueryContext(ctx, getVaccinationRecordsByPatientID, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaccinationRecord{}
	for rows.Next() {
		var i VaccinationRecord
		if err := rows.Scan(
			&i.ID, &i.CreatedAt, &i.PatientID, &i.RecordedBy,
			&i.VaccineName, &i.DateAdministered, &i.LotNumber, &i.Site, &i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
