// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"database/sql"
)

const createVitalSign = `-- name: CreateVitalSign :exec
INSERT INTO vital_signs (id, created_at, patient_id, recorded_by, systolic_bp, diastolic_bp, heart_rate, temperature, temp_route, oxygen_sat, respirations, pain_level, supplemental_o2, o2_flow_rate, position, notes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateVitalSignParams struct {
	ID             string
	CreatedAt      string
	PatientID      string
	RecordedBy     string
	SystolicBp     sql.NullInt64
	DiastolicBp    sql.NullInt64
	HeartRate      sql.NullInt64
	Temperature    sql.NullFloat64
	TempRoute      sql.NullString
	OxygenSat      sql.NullInt64
	Respirations   sql.NullInt64
	PainLevel      sql.NullInt64
	SupplementalO2 int64
	O2FlowRate     sql.NullFloat64
	Position       sql.NullString
	Notes          string
}

func (q *Queries) CreateVitalSign(ctx context.Context, arg CreateVitalSignParams) error {
	_, err := q.db.ExecContext(ctx, createVitalSign,
		arg.ID, arg.CreatedAt, arg.PatientID, arg.RecordedBy,
		arg.SystolicBp, arg.DiastolicBp, arg.HeartRate, arg.Temperature,
		arg.TempRoute, arg.OxygenSat, arg.Respirations, arg.PainLevel,
		arg.SupplementalO2, arg.O2FlowRate, arg.Position, arg.Notes,
	)
	return err
}

const getVitalSignsByPatientID = `-- name: GetVitalSignsByPatientID :many
SELECT id, created_at, patient_id, recorded_by, systolic_bp, diastolic_bp, heart_rate, temperature, temp_route, oxygen_sat, respirations, pain_level, supplemental_o2, o2_flow_rate, position, notes
FROM vital_signs
WHERE patient_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetVitalSignsByPatientID(ctx context.Context, patientID string) ([]VitalSign, error) {
	rows, err := q.db.QueryContext(ctx, getVitalSignsByPatientID, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VitalSign{}
	for rows.Next() {
		var i VitalSign
		if err := rows.Scan(
			&i.ID, &i.CreatedAt, &i.PatientID, &i.RecordedBy,
			&i.SystolicBp, &i.DiastolicBp, &i.HeartRate, &i.Temperature,
			&i.TempRoute, &i.OxygenSat, &i.Respirations, &i.PainLevel,
			&i.SupplementalO2, &i.O2FlowRate, &i.Position, &i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestVitalSign = `-- name: GetLatestVitalSign :one
SELECT id, created_at, patient_id, recorded_by, systolic_bp, diastolic_bp, heart_rate, temperature, temp_route, oxygen_sat, respirations, pain_level, supplemental_o2, o2_flow_rate, position, notes
FROM vital_signs
WHERE patient_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestVitalSign(ctx context.Context, patientID string) (VitalSign, error) {
	row := q.db.QueryRowContext(ctx, getLatestVitalSign, patientID)
	var i VitalSign
	err := row.Scan(
		&i.ID, &i.CreatedAt, &i.PatientID, &i.RecordedBy,
		&i.SystolicBp, &i.DiastolicBp, &i.HeartRate, &i.Temperature,
		&i.TempRoute, &i.OxygenSat, &i.Respirations, &i.PainLevel,
		&i.SupplementalO2, &i.O2FlowRate, &i.Position, &i.Notes,
	)
	return i, err
}

const getVitalSignByID = `-- name: GetVitalSignByID :one
SELECT id, created_at, patient_id, recorded_by, systolic_bp, diastolic_bp, heart_rate, temperature, temp_route, oxygen_sat, respirations, pain_level, supplemental_o2, o2_flow_rate, position, notes
FROM vital_signs
WHERE id = ?
`

func (q *Queries) GetVitalSignByID(ctx context.Context, id string) (VitalSign, error) {
	row := q.db.QueryRowContext(ctx, getVitalSignByID, id)
	var i VitalSign
	err := row.Scan(
		&i.ID, &i.CreatedAt, &i.PatientID, &i.RecordedBy,
		&i.SystolicBp, &i.DiastolicBp, &i.HeartRate, &i.Temperature,
		&i.TempRoute, &i.OxygenSat, &i.Respirations, &i.PainLevel,
		&i.SupplementalO2, &i.O2FlowRate, &i.Position, &i.Notes,
	)
	return i, err
}
